# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8f0b46eb741ab2adf08e0a5409c0f272bdc76b896818aa7ec658db4d8c617aa97deda05088431bf96786cdf7ad2d6e6cd445cb44d6de1a4af29d677d39fe3b2

test:
  secret_key_base: f1864d0e1de0d7bd5436d53319e6af3c46e1b3ffbccb37b48b2fea87a85234fe0d61497efbb0b3eb3b89a8cbd5361a189c91578537d7d74c43335a7eaed691f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
